RM76459
LUCAS MAROPO RODRIGUES

JUNIT:
	import junit.framework.TestCase;
	import org.junit.*;

	public class TesteJulgamentoPrisioneiro extends TestCase{
		@Test
		public void testCalculaPena() {
			String respostaPrisioneiroA = "Inocente"; 
			String respostaPrisioneiroB = "Inocente"; 
			JulgamentoPrisioneiro julgamento = new JulgamentoPrisioneiro(); 
			
			int resultadoEsperado = 0; 
			int resultadoReal = julgamento.calculaPena(respostaPrisioneiroA, respostaPrisioneiroB);
			
			assertEquals(resultadoEsperado, resultadoReal);
		}
	}

1° Execução:
	Erros:
		Descrição:
			O erro ocorreu devido ao fato do método calculaPena da Classe JulgamentoPrisioneiro esperar como parâmetros para o método 
				a respostaPrisioneiroA e respostaPrisioneiroB do tipo "Resposta", acredito que a idéia do desenvolvedor era criar uma 
				classe model Resposta que possuiria como atributo a resposta do prisioneiro o que difere do solicitado pelo cliente.
		Log:
			java.lang.Error: Unresolved compilation problem: 
				The method calculaPena(Resposta, Resposta) from the type JulgamentoPrisioneiro refers to the missing type Resposta
					at TesteJulgamentoPrisioneiro.testCalculaPena(TesteJulgamentoPrisioneiro.java:12)
					at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
					at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
					at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
					at java.base/java.lang.reflect.Method.invoke(Method.java:567)
					at junit.framework.TestCase.runTest(TestCase.java:176)
					at junit.framework.TestCase.runBare(TestCase.java:141)
					at junit.framework.TestResult$1.protect(TestResult.java:122)
					at junit.framework.TestResult.runProtected(TestResult.java:142)
					at junit.framework.TestResult.run(TestResult.java:125)
					at junit.framework.TestCase.run(TestCase.java:129)
					at junit.framework.TestSuite.runTest(TestSuite.java:252)
					at junit.framework.TestSuite.run(TestSuite.java:247)
					at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
					at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
					at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
					at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
					at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
					at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
					at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
					
2° Execução:
	Correção:
		JulgamentoPrisioneiro:
			calculaPena:
				public int calculaPena(String respostaPrisioneiroA, String respostaPrisioneiroB)
				
	Erros:
		O erro ocorreu devido a ausência da contante Resposta.DELACAO, que não existe pois a classe Resposta não existe.
	Log:
		java.lang.Error: Unresolved compilation problems: 
			Resposta cannot be resolved to a variable
			Resposta cannot be resolved to a variable
			Resposta cannot be resolved to a variable

				at JulgamentoPrisioneiro.calculaPena(JulgamentoPrisioneiro.java:8)
				at TesteJulgamentoPrisioneiro.testCalculaPena(TesteJulgamentoPrisioneiro.java:12)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:567)
				at junit.framework.TestCase.runTest(TestCase.java:176)
				at junit.framework.TestCase.runBare(TestCase.java:141)
				at junit.framework.TestResult$1.protect(TestResult.java:122)
				at junit.framework.TestResult.runProtected(TestResult.java:142)
				at junit.framework.TestResult.run(TestResult.java:125)
				at junit.framework.TestCase.run(TestCase.java:129)
				at junit.framework.TestSuite.runTest(TestSuite.java:252)
				at junit.framework.TestSuite.run(TestSuite.java:247)
				at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
				at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
				at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
				at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
				at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
				at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
				at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
				
3° Execução:
	Correção:
		JulgamentoPrisioneiro:
			calculaPena:
				if (respostaPrisioneiroA == "Culpado") {
					if (respostaPrisioneiroB == "Culpado") {
					
				if (respostaPrisioneiroB == "Culpado") {
				
	Erros:
		Erro de lógica, de acordo com o algoritimo passado pelo cliente quando os dois prisioneiros informassem
			respostas diferentes de "Culpado" o algoritimo deveria retornar 0 (PENA_INOCENCIA) porém o mesmo retornou
			11	
	Log:
		junit.framework.AssertionFailedError: expected:<0> but was:<11>
			at junit.framework.Assert.fail(Assert.java:57)
			at junit.framework.Assert.failNotEquals(Assert.java:329)
			at junit.framework.Assert.assertEquals(Assert.java:78)
			at junit.framework.Assert.assertEquals(Assert.java:234)
			at junit.framework.Assert.assertEquals(Assert.java:241)
			at junit.framework.TestCase.assertEquals(TestCase.java:409)
			at TesteJulgamentoPrisioneiro.testCalculaPena(TesteJulgamentoPrisioneiro.java:14)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:567)
			at junit.framework.TestCase.runTest(TestCase.java:176)
			at junit.framework.TestCase.runBare(TestCase.java:141)
			at junit.framework.TestResult$1.protect(TestResult.java:122)
			at junit.framework.TestResult.runProtected(TestResult.java:142)
			at junit.framework.TestResult.run(TestResult.java:125)
			at junit.framework.TestCase.run(TestCase.java:129)
			at junit.framework.TestSuite.runTest(TestSuite.java:252)
			at junit.framework.TestSuite.run(TestSuite.java:247)
			at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
			at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
			at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
